---

- name: Restart zabbix-agent
  service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
  become: yes

- name: Restart zabbix-agent (entware)
  command: /opt/etc/init.d/S07zabbix_agentd restart

